"""Added first_name and last_name to employees

Revision ID: 00164e3e177a
Revises: 
Create Date: 2025-02-10 16:32:49.721251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '00164e3e177a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.add_column('employees', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.drop_column('employees', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('employees', 'last_name')
    op.drop_column('employees', 'first_name')
    op.alter_column('companies', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
