"""Alter comlumn nullable in meetings and employees

Revision ID: 58d9d90978ec
Revises: 5e8f1717065b
Create Date: 2025-02-11 13:34:45.041060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '58d9d90978ec'
down_revision: Union[str, None] = '5e8f1717065b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_meetings')
    op.drop_column('meetings', 'stop_time')
    op.drop_column('meetings', 'start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('start_time', mysql.DATETIME(), nullable=True))
    op.add_column('meetings', sa.Column('stop_time', mysql.DATETIME(), nullable=True))
    op.create_table('employee_meetings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employee_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='employee_meetings_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name='employee_meetings_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
