"""changed meetin tableg date type to datetime

Revision ID: ef4c2b37f8be
Revises: 00164e3e177a
Create Date: 2025-02-10 16:51:05.520964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef4c2b37f8be'
down_revision: Union[str, None] = '00164e3e177a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'date',
               existing_type=sa.String(length=255),
               type_=sa.DateTime())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'date',
               existing_type=sa.DateTime(),
               type_=sa.String(length=255))
    # ### end Alembic commands ###
